// ============================================================
//  COURIER RATE DATA
//  AUTO-GENERATED by sync_rates.py -- do not edit by hand.
//
//  To update: edit a .md file in this folder, then run:
//      python sync_rates.py
//  from the "Courier Comparison" directory.
//
//  Source files:
//    rates/inpost.md
//    rates/royal-mail.md
//    rates/evri.md
//    rates/dpd.md
//    rates/dhl.md
//
//  Last synced: 2026-03-27
// ============================================================

const RATE_DATA = {

  // -- InPost -- source: rates/inpost.md
  inpost_inject: { '0-2': 1.93, '2-3': 1.93, '3-15': 2.48, '15-20': 3.57, '20-30': 3.57 },

  inpost_collect: { '0-2': 2.17, '2-3': 2.17, '3-15': 2.72, '15-20': 3.81, '20-30': 3.81 },

  // -- InPost Next Day (indicative) -- source: rates/inpost.md
  inpost_nd_inject: { '0-2': 2.89, '2-3': 2.89, '3-15': 3.17, '15-20': null, '20-30': null },

  inpost_nd_collect: { '0-2': 3.13, '2-3': 3.13, '3-15': 3.41, '15-20': null, '20-30': null },

  // -- Evri (via MHI) -- source: rates/evri.md
  evri_std: { '0-2': 2.35, '2-3': 3.63, '3-15': 3.63, '15-20': 8.90, '20-30': 10.35 },

  evri_nd: { '0-2': 3.45, '2-3': 4.08, '3-15': 4.08, '15-20': 9.35, '20-30': 11.40 },

  // -- Royal Mail -- source: rates/royal-mail.md
  rm_t48: { '0-2': 2.50, '2-3': 2.50, '3-15': null, '15-20': null, '20-30': null },

  rm_t24: { '0-2': 2.95, '2-3': 2.95, '3-15': null, '15-20': null, '20-30': null },

  // -- DPD -- source: rates/dpd.md
  dpd_nd: { '0-2': 4.80, '2-3': 4.80, '3-15': 4.80, '15-20': 4.80, '20-30': 4.80 },

  // -- DHL eCommerce -- source: rates/dhl.md
  dhl_nd: { '0-2': 4.65, '2-3': 4.65, '3-15': 4.65, '15-20': 4.65, '20-30': 4.65 },

};
